import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import connectDB from "@/lib/mongodb";
import { AuthProvider } from "@/providers/AuthProvider";
import NextAuthProvider from "@/providers/NextAuthProvider"; // 👈

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  await connectDB();
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <NextAuthProvider> {/* 👈 */}
          <AuthProvider>
            <Navbar />
            <main className="lg:py-8 md:py-6 py-4">{children}</main>
          </AuthProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}